### PR TITLE
Update the docs with the order of transforms

### PR DESCRIPTION
**Pull request by silvenon**
Whew, it took me a while to figure out what I'm doing wrong, I hope this will help someone else.

Did I write it correctly? I'm new to Browserify.

### CODE REVIEW

**Comment by bendrucker** [comment]
I'd phrase it like this instead:

> Browserify transforms are run in order and may modify your source code along the way. You'll typically want to include browserify-shim last.

**Comment by silvenon** [comment]
Updated.

**Comment by bendrucker** [comment]
Great. @thlorenz this cool with you?

**Comment by thlorenz** [comment]
LGTM, please merge to master.
However an npm publish is not needed at this point.

**Comment by bendrucker** [comment]
Merged as 50f17793d236677a4e0664525a8311ae0d527458

**Pull request closed without merging**
