### PR TITLE
Added the ability to accept multiple-exports

### PR DESCRIPTION
**Pull request by EvanCarroll**
Now exports as defined in the json can accept an Array
	ex., js.js: { exports => ["foo","bar"] }

### CODE REVIEW

**Comment by bendrucker** [comment]
This needs tests

**Comment by thlorenz** [comment]
I'm a bit on the fence about this, it complicates the code quite a bit.

Also we need an update to the README for this and I expect it will make it harder to understand how to use browserify-shim for the current use case if we were to document everywhere "oh btw and you can pass an array here as well".
So if we do document it, it'd be better inside a separate section, i.e *How to export multilpe globals" which most users could safely ignore.

And yes agreed this needs tests.

**Comment by EvanCarroll** [comment]
This still doesn't work for my purposes. I still can't figure out how to get Prototype.js shimmed.

**Comment by bendrucker** [comment]
In that case it doesn't make sense to make the effort and add extra complexity. Closing.

**Pull request closed without merging**
